spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyline_test
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop