spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyline_prod
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none