server:
  port: 8080
spring:
  application:
    name: .
  datasource:
    url: jdbc:mysql://localhost:3306/eazyline?useSSL=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


